# Generated by Django 2.0.9 on 2019-01-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190103_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvoted',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
