# Generated by Django 2.0.9 on 2019-01-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190103_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='up',
        ),
    ]
