# Generated by Django 2.0.9 on 2019-01-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190103_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
